name: TestPlugin2
version: 1.0.0
main: io.github.sahibkhokhar.TestPlugin2
description: A test plugin number 2
author: Sahib Khokhar
api-version: 1.19
commands:
  craft:
    description: Opens inv
    usage: /<command>